# num_ex예제
## 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
a1.dtype

dtype('int32')

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [5]:
a2.dtype

dtype('float64')

In [6]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [7]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 범위를 지정해 배열 생성

1. arr_obj = np.arange([start,] stop[,step])
 - start부터 stop 전까지 step만큼 더해 배열을 생성
 - start 디폴트는 0
 - step 디폴트는 1

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
a1 = np.arange(1, 10)
a1.shape # data type = tuple, shape는 원소의 갯수를 리턴해주는 함수

(9,)

In [16]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2.shape # shape(행 횟수, 컬럼횟수)

(3, 3)

2. reshape(m, n)
 - 배열의 차원 조정
 - m x n 행태로 변경
 - 데이터의 개수가 맞아야 함 (ex: 12개의 데이터를 3 by 3 행렬로 표현못함)
 - 1차원 배열 - 벡터, 2차원 배열 - 행렬, n차원 이상 - n차원 행렬, 전체 - Tensor 

In [17]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [20]:
b2 = np.arange(5)
b2.shape

(5,)

2. arr_obj = np.linspace(start, stop[, num])
 - start부터 stop까지(포함) num개의 NumPy 배열 생성
 - num 디폴트 값은 1

In [22]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.linspace(0, np.pi, 20) # 0부터 pi(3.14) 까지 20개 값을 균일한 간격으로 출력

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

1. 원소가 0인 배열 생성 
 - arr_zero_n = np.zeros(n)
 - arr_zero_mxn = np.zeros((m,n))
2. 원소가 1인 배열 생성
 - arr_one_n = np.ones(n)
 - arr_one_mxn = np.ones((m,n))

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,4,3)) # RGB 채널 표현 방법

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

○ n x n 단위 행렬(행렬의대각선이) 1인 행렬 생성
 - arr_I = np.eye(n)

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

○ 배열을 지정한 타입으로 변환
 - arr_obj = np.astype(타입)

In [30]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [31]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [34]:
str_a1.dtype

dtype('<U5')

In [33]:
num_a1.dtype

dtype('float64')

In [35]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [36]:
str_a2.dtype

dtype('<U1')

In [37]:
num_a2.dtype

dtype('int32')

1. 난수 배열의 생성
- np.random.seed(시드값)
 -- 난수 생성 시드값 설정
- rand_num = np.random.rand()
 - [0. 1) 사이의 실수 난수 생성
- rand_num = np.random.rand([d0, d1, …, dn])
 -- 지정한 차원의 배열 생성
- [0. 1) 사이의 실수 난수로 채움
 -- rand_num = np.random.randn([d0, d1, …, dn])
- 지정한 차원의 배열 생성
 -- 가우시안 표준 정규 분포를 따르는 실수 난수 채움
- rand_num = np.random.randint([low,] high, [,size])
 -- [low, high)사이의 정수 난수를 갖는 배열 생성
 -- size는 배열의 크기
  --- 튜플로 지정 (d0, d1, … , dn)
 -- low의 디폴트 값은 0

In [38]:
np.random.rand(2,3)

array([[0.79128369, 0.23932651, 0.73968998],
       [0.67559116, 0.64839354, 0.34476184]])

In [39]:
np.random.rand()

0.3101431953955409

# 기본연산

In [40]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
arr1 + arr2

array([11, 22, 33, 44])

In [41]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [42]:
arr2 * 2

array([2, 4, 6, 8])

In [43]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [44]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [45]:
arr1 / arr2

array([10., 10., 10., 10.])

In [46]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [47]:
arr1 > 20

array([False, False,  True,  True])

## 배열의 인덱싱과 슬라이싱

- 배열명[위치]
- 배열명[[위치1, 위치2, …, 위치n]]
 - 해당 차원의 여러 원소 선택
- 배열명[행_위치, 열_위치]
- 배열명[ [행_위치1, 행_위치2, … , 행_위치n],
        [열_위치1, 열_위치2, … , 열_위치n]]
 - 2차원 배열의 여러 원소를 선택
- 배열명[조건식]
 - 해당 조건식을 만족하는 원소만 선택된 배열

In [48]:
a1 = np.array([0, 10, 20, 30, 40, 50])

In [49]:
a1[0]

0

In [50]:
a1[4]

40

In [54]:
a1[5]=70
a1

array([ 0, 10, 20, 30, 40, 70])

In [55]:
a1[[1,3,4]]

array([10, 30, 40])

In [58]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [59]:
a2[0,2]

30

In [60]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [61]:
a2[1]

array([40, 50, 60])

In [63]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [64]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [65]:
a2[[0, 2], [0, 1]] # (0,0), (1,1) 행렬 만 출력

array([10, 80])

In [66]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

In [67]:
a[(a % 2) == 0]

array([2, 4, 6])

- 배열[시작_위치:끝_위치]
 - 시작_위치 ~ 끝_위치-1 범위의 슬라이싱
 - 시작_위치 생략시 0
 - 끝_위치 생략시 배열의 끝
- 배열[행시작_위치:행끝_위치, 열시작_위치:열끝_위치]
 - 2차원의 슬라이싱

In [68]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [69]:
b1[:3]

array([ 0, 10, 20])

In [70]:
b1[2:]

array([20, 30, 40, 50])

In [71]:
b1[2:5] = np.array([25,35,45]) # 리스트랑 다른점 : 리스트는 읽기만 가능하지만 배열은 수정가능
b1

array([ 0, 10, 25, 35, 45, 50])

In [73]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [74]:
b2 = np.arange(10, 100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [75]:
b2[1:3, 1:3] # 이미지 crop과 비슷, 좌표 (1,1) ~ (3,3) 까지만 보여줌

array([[50, 60],
       [80, 90]])

In [80]:
b2[:3, 1:]

array([[25, 35],
       [55, 65],
       [80, 90]])

In [77]:
b2[1][0:2]

array([40, 50])

In [83]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [81]:
np.array([1,2])

array([1, 2])